version: "2.3"

services:
  node:
    environment:
      - BUILDKITE
      - BUILDKITE_ARTIFACT_PATHS
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_CREATOR
      - BUILDKITE_BUILD_CREATOR_EMAIL
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMAND
      - BUILDKITE_COMMIT
      - BUILDKITE_JOB_ID
      - BUILDKITE_LABEL
      - BUILDKITE_MESSAGE
      - BUILDKITE_ORGANIZATION_SLUG
      - BUILDKITE_PIPELINE_DEFAULT_BRANCH
      - BUILDKITE_PIPELINE_PROVIDER
      - BUILDKITE_PIPELINE_SLUG
      - BUILDKITE_PLUGINS
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_PULL_REQUEST_BASE_BRANCH
      - BUILDKITE_PULL_REQUEST_REPO
      - BUILDKITE_REBUILT_FROM_BUILD_ID
      - BUILDKITE_REBUILT_FROM_BUILD_NUMBER
      - BUILDKITE_REPO
      - BUILDKITE_REPO_SSH_HOST
      - BUILDKITE_RETRY_COUNT
      - BUILDKITE_SCRIPT_PATH
      - BUILDKITE_SOURCE
      - BUILDKITE_TAG
      - BUILDKITE_TIMEOUT
      - BUILDKITE_TOKEN
      - BUILDKITE_TRIGGERED_FROM_BUILD_ID
      - CI
      - GITHUB_TOKEN
      - NPM_TOKEN

  node-14:
    environment:
      - BUILDKITE
      - BUILDKITE_ARTIFACT_PATHS
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_CREATOR
      - BUILDKITE_BUILD_CREATOR_EMAIL
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMAND
      - BUILDKITE_COMMIT
      - BUILDKITE_JOB_ID
      - BUILDKITE_LABEL
      - BUILDKITE_MESSAGE
      - BUILDKITE_ORGANIZATION_SLUG
      - BUILDKITE_PIPELINE_DEFAULT_BRANCH
      - BUILDKITE_PIPELINE_PROVIDER
      - BUILDKITE_PIPELINE_SLUG
      - BUILDKITE_PLUGINS
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_PULL_REQUEST_BASE_BRANCH
      - BUILDKITE_PULL_REQUEST_REPO
      - BUILDKITE_REBUILT_FROM_BUILD_ID
      - BUILDKITE_REBUILT_FROM_BUILD_NUMBER
      - BUILDKITE_REPO
      - BUILDKITE_REPO_SSH_HOST
      - BUILDKITE_RETRY_COUNT
      - BUILDKITE_SCRIPT_PATH
      - BUILDKITE_SOURCE
      - BUILDKITE_TAG
      - BUILDKITE_TIMEOUT
      - BUILDKITE_TOKEN
      - BUILDKITE_TRIGGERED_FROM_BUILD_ID
      - CI
      - GITHUB_TOKEN
      - NPM_TOKEN
